//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string CONTRASEÑA { get; set; }
        public Nullable<int> ACCESO { get; set; }
    }
}
